modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="better_tools"
version="10.3.1"
displayName="Better Tools and Armor"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-tools-and-armor"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="BlackCatGamer64, MCreator"
description="Adds new ores, tools, armor, music discs, enchantments, food, potion effects and much more!"

[[dependencies.better_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"



[[dependencies.better_tools]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

