modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="better_tools"
version="11.0"
displayName="Better Tools and Armor"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-tools-and-armor"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="BlackCatGamer64, MCreator"
description="Adds many new ores and resources which improve the progression and exploration in Minecraft. Also adds many misc. features"

[[dependencies.better_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"


[[dependencies.better_tools]]
    modId="curios"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_tools]]
    modId="jei"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.better_tools]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_tools]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

